### ISSUE TITLE
Coordinator Dashboard: Case tracker for Applications

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#264]
### Overview
As a Coordinator I want a case tracker for the applications so I know where the hosts and guests are in the system and track their progress

### Action Items
- [ ] Product
   - [ ] Gather requirements 
      - [ ] Sorting method to see hosts or guests
      - [ ] Show time elapsed for how long it's taken for guest/host to be approved (And push hosts/guests with higher wait time to top of the screen)
      - [ ] Approvals for the Coordinator to confirm hosts/guests information
           - [ ] Need a box on the current application screens (where applicable) for Coordinator to approve that specific screen within that hosts/guests application (Instead of making new screens we will just add an approval box to the current screens)
    - [ ] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create Case Tracker Screen
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Questions
1. Do the coordinators see the application before it get submitted? Do they only see fully submitted applications?
2. Should approvals be it's own ticket?

**Comment by juliaa423** [comment]
Added wireframe to "Dashboard wireframes" Figma page. There are comments on there about what content would fall under each column. Is the goal to have a line by line view or alternate views (progress bar, pie chart) as well?

**Comment by quyenvhle** [comment]
Duplicate with #284 , therefore close.
