### ISSUE TITLE
Coordinator Dashboard: Onboarding Tracker

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#265]
### Overview
As a Coordinator I want a case tracker for onboarding so I know where the hosts and guests are in the system and track their progress

### Action Items
- [ ] Product
   - [ ] Gather requirements 
      - [ ] Sorting method to see hosts or guests
      - [ ] Show time elapsed to determine how long host/guest has been at each stage of onboarding 
    - [ ] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create Case Tracker Screen
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Questions

**Comment by juliaa423** [comment]
Added wireframe to "Dashboard wireframes" Figma page. Feel free to leave comments/questions there for future iterations. Is the goal to have a line by line view or alternate views (progress bar, pie chart) as well?

**Comment by quyenvhle** [comment]
Duplicate with #284. therefore close.
