### ISSUE TITLE
Application Tracker Host: Design

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#280]
### Overview
As a Host, I want to know where I'm at in the process

### Action Items
- [ ] Design screens based on following requirements
  - [x] Display the following stages of the Host
    - Application Received
    - Application Approved
    - Pre-match Meetings Completed
      - Interview
      - Home Inspection
      - Orientation
      - Training
    - Match Received
    - Preliminary Meetings Completed
      - Meeting at SPY with Guest
      - Meeting at home with Guest
    - Match Finalized 
  - [x] Allow Host to see which stages they have completed and which stages they have not
  - [x] Display dates that the Host pass through the corresponding stages
  - [ ] Allow Host to view the Guest(s) profile(s) - #304 
  - [ ] Allow Host to confirm if they want to be matched with the Guest - #
  - [x] Notify the Host of when to schedule meetings

### Resources/Instructions
[MVP Zero-fi
](https://docs.google.com/presentation/d/1RhvqZfcLfyiokpuB9tGcR7oZ2zclDMaq9NT4NEckD1I/edit#slide=id.gca2d33aa22_0_996)

**Comment by kpoints** [comment]
Majority of these tasks have been completed. The following tasks will be reopened as separate issues when the requirements have been further defined: 

- Hosts can only view Guests if a Guest has selected them as a requested potential Host Match
- Hosts confirm for initial match interviews and have multiple steps they will confirm moving forward with the matching process.
