### ISSUE TITLE
MVP Guest Application Tracker

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#281]
### Overview
As a Guest, I want to know where I'm at in the process

Edited 4/27/2021

### Action Items
- [x]  Product
  - [x] Gather requirements
- [ ] Design
  - [ ] Display the following stages of the Guest
    - [x] Application Received
    - [x] Application Approved
    - [x] Pre-match Meetings Completed
      - [x] Interview
      - [x] Training
    - [ ] PICK YOUR HOST (Please make this a button, it will take them to the potential HOST location, will only work for single guests for MVP, coguests will not see this button and will need to go to the office to pick a Host or will need to be emailed the profiles)
    - [x] Host Selected
    - [x] Match Received
    - [x] Preliminary Meetings Completed
      - [x] Meet host at SPY
      - [x] Meet host at Home
    - [x] Match Finalized 
  - [x] Allow Guest to see which stages they have completed and which stages they have not
  - [x] Display dates that the Guest pass through the corresponding stages
  - [ ] Allow Guest to view potential Host(s) profile(s)
  - [x] Notify Guest of when to schedule meetings (showing some lines or pop up on the screen, for example)

### Resources/Instructions
[MVP Zero-fi
](https://docs.google.com/presentation/d/1RhvqZfcLfyiokpuB9tGcR7oZ2zclDMaq9NT4NEckD1I/edit#slide=id.gc8864b72d9_0_0)

**Comment by abbyhipp** [comment]
Please view comment 34-36 in Figma

**Comment by lola3736** [comment]
This issue has been replaced by [#533 Section 2 Guest Intake Profile (fka Application Form)](#533).
