### ISSUE TITLE
Coordinator Dashboard: Epic

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#318]
### Overview
As a Coordinator I want to manage the applications, participants (Guest & Host), and matches of the Host Home Program.

### Action Items
- Product
   - [x] Gather design requirements
   - [x] Create master design ticket - #284 
   - [x] Discuss with Designers
- UI/UX
   - [ ] Create Coordinator Dashboard - #284

- Product
   - [ ] Gather dev requirements
   - [ ] Create master dev ticket
   - [ ] Handoff to dev   
- Development   
   - [ ] Develop feature - #

### Resources/Instructions
https://docs.google.com/presentation/d/1RhvqZfcLfyiokpuB9tGcR7oZ2zclDMaq9NT4NEckD1I/edit#slide=id.gc6803e55d3_0_0

**Comment by fourmatte** [comment]
Currently working screens that allow coordinator to edit/update guest/host/matches screens 

https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1355%3A1

Estimated time for Tuesday, August 10, 2021.

**Comment by fourmatte** [comment]
Currently working screens that allow coordinator to edit/update guest/host/matches screens 

https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1355%3A1

Estimated time for Tuesday, August 10, 2021.

**Comment by JRHutson** [comment]
Removing Role- Product Management Label. When ready to hand off to the dev team, let's place the issue in the For Review column to ensure the PM team knows to facilitate.

**Comment by fourmatte** [comment]
Action items for 9/1/21:

- Under matches, combine the guest and host into a greater row with guest and host listed in sub-rows with their 
respective notes/status etc.

**Comment by kpoints** [comment]
We are closing this as we'll be utilizing the updated User Stories to keep track of the application information and converting those user stories into individual issues that we can assign to individual contributors.

**Comment by lola3736** [comment]
This issue has been replaced by [#454 Coordinator](#454).
