### ISSUE TITLE
Application Tracker Host: Epic

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#319]
### Overview
As a Host, I want to know where I'm at in the process

### Action Items
- Product
   - [x] Gather design requirements
   - [x] Create master design ticket - #280 
   - [x] Discuss with Designers
- UI/UX
   - [ ] Design Application Tracker - #280 

- Product
   - [x] Gather dev requirements
   - [x] Create master dev ticket - #290 
   - [ ] Handoff to dev   
- Development   
   - [ ] Develop feature - #290

**Comment by JRHutson** [comment]
Removing Role- Product Management Label. When ready to hand off to the dev team, let's place the issue in the For Review column to ensure the PM team knows to facilitate.

**Comment by kpoints** [comment]
We are closing this as we'll be utilizing the updated User Stories to keep track of the application information and converting those user stories into individual issues that we can assign to individual contributors.

**Comment by lola3736** [comment]
This issue has been replaced by [#456 Section Host Epic](#456)
