### ISSUE TITLE
Application Tracker Guest: Epic

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#322]
### Overview
As a Guest, I want to know where I'm at in the process

### Action Items
- Product
   - [x] Gather design requirements
   - [x] Create master design ticket - #281 
   - [x] Discuss with Designers
- UI/UX
   - [ ] Design Application Tracker - #281  

- Product
   - [x] Gather dev requirements
   - [x] Create master dev ticket - #290 
   - [ ] Handoff to dev   
- Development   
   - [ ] Develop feature - #290

**Comment by kpoints** [comment]
We are closing this as we'll be utilizing the updated User Stories to keep track of the application information and converting those user stories into individual issues that we can assign to individual contributors.

**Comment by lola3736** [comment]
This issue has been replaced with [#533 Section 2 Guest Intake Profile (fka Application Form)](#533)
