### ISSUE TITLE
Review Epic to determine issues that need to be made.

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#323]
**UPDATE LABELS: Add the following labels to each new issue, and remove defaults:**
* Role
* Feature
* Points 
* Milestone

### Overview
We need to review requirements so that we can make issues and define behavior for features.

### Action Items
Review check boxes below to determine what items need to be made into issues.

### Overview
As a Coordinator, I want to manage the applications, participants (Guest & Host), and matches of the Host Home Program.

### Action Items
- [ ] Design screens based on following requirements:
   - [ ] Coordinator can view all applications submitted, categorized by Guest and Host and can click on the Guest/Host name to pull up their application/information in each stage they are in
   - [ ] Coordinator has a text area to input information about each Host/Guest for explanation of why they are in certain stages or if extra explanation is required
   - [ ] Coordinator can view which Guest/Host are in which states (stages)
       - [ ] Stage 1: Application Received
       - [ ] Stage 2: Application Approved
       - [ ] Stage 3: Pre-match Meetings Completed
            - [ ] Stage 3.1: Interview
            - [ ] Stage 3.2: Training
       - [ ] Stage 4: Host Selected by guest, Host is moved into a 'waiting zone' until they approve/deny the match
       - [ ] Stage 5: Match Received, Host has approved the match
       - [ ] Stage 6: Preliminary Meetings Completed
            - [ ] Stage 6.1: Guest and Host meet at SPY
            - [ ] Stage 6.2: Guest and Host meet at Hosts Home
       - [ ] Stage 7: Match Finalized
       - [ ] Stage 0: Holding Zone (Used for anyone the coordinator needs to move out of our current system: Respite, people on vacation etc)
   - [ ] Coordinator can approve/deny applications
   - [ ] Coordinator can move Guest/Host across states (stages)
   - [ ] Coordinator can link Guest with Co-guest
   - [ ] Coordinator can match Guest with potential Hosts by using the HUU "Match" button which will use our automated system to match Guests and Hosts against the various qualifying questions
   - [ ] Coordinator can finalize the match (assigning one of the potential Hosts for the Guest)
   - [ ] Coordinator can revert the match and select status for guest/host (Create Hold/Unmatch button for post-matches that coordinator's can click at any time to rematch)
   - [ ] Coordinator can add guests (Guests have to be added to the system, the coordinator will have a screen or pop up that allows them to add the guests email address. This will send an email to the guest inviting them to join HUU) - #295 

### Resources/Instructions
https://docs.google.com/presentation/d/1RhvqZfcLfyiokpuB9tGcR7oZ2zclDMaq9NT4NEckD1I/edit#slide=id.gc6803e55d3_0_0

**Comment by sanya301** [comment]
@lasryariel this seems like a legacy ticket, can you take a look to see if this is still needed?

**Comment by lasryariel** [comment]
legacy ticket.
