### ISSUE TITLE
Create High-Level Roadmap and Add to Wiki

### ISSUE THREAD

**Issue by rossbb** [hackforla/HomeUniteUs#428]
### Overview
Create a high-level roadmap for the project to help the team monitor and manage the project as a whole.

### Action Items
 - [ ] Create High-level roadmap document
 - [ ] Add initial roadmap stages/items 
 - [ ] Share roadmap with team
 - [ ] Teach team how to use and maintain roadmap

### Resources/Instructions
Resources:
 - https://github.com/hackforla/product-management/wiki/Milestones
 - https://www.linkedin.com/learning/product-management-building-a-product-roadmap
 - [HfLA's roadmap guide - very out date](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)

Examples of other project's roadmaps

[Open Community Survey Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)
[Guides Team Roadmap Example](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
Guides Team Milestones https://github.com/hackforla/guides/milestones
