### ISSUE TITLE
Update the HUU HfLA Page

### ISSUE THREAD

**Issue by brycelednar** [hackforla/HomeUniteUs#445]
#### Objective

Update content on the [Home Unite Us page](https://www.hackforla.org/projects/home-unite-us) on hackforla.org 

#### Content Updates

* Technologies:
   * Remove: auth0
   * Add: AWS Cognito

* Product Team Meeting
   * Update time to: Mon 5:40 pm to 6:10 pm

* Current Project Team
  * Remove 
    * Kristelle Gumaru
  * Add 
    * Samuel Kowitch
      * UX/UI Designer
      * GitHub: KowDesign
      * Slack: U04GYSFB98X
    * Muyin Zheng
      * UX/UI Designer
      * GitHub: IndigoYinZ
      * Slack: U04HAEEKT29
     * Emily Eldar
       * Developer
       * GitHub: emeldar
       * Slack: U04BEDM1B2L

#### Tasks

- [x] List content updates in this issue
- [x] Confirm content updates are comprehensive
- [x] Link this issue to VRMS 1274
