### ISSUE TITLE
Create a budget for funding

### ISSUE THREAD

**Issue by brycelednar** [hackforla/HomeUniteUs#446]
#### Objective

Provide a budget for Home Unite Us as an input for funding conversations.

#### Tasks

- [x] Identify example budgets and best practices
- [x] Create a budget document
- [x] Identify key line items
- [x] Provide estimates for key line items
- [x] Update with research plan

**Comment by brycelednar** [comment]
Hi @rpbracker, @tylerthome, and @erikguntner, 

As mentioned on Tuesday, I had a productive discussion with Bonnie and we are making progress toward starting funding discussions soon. To help construct the budget, can you let me know the tools/services that you anticipate will be needed for HUU and any specifics on plan and price (if known)? This should include hosting, db, and any other AWS service we anticipate using. Thank you!

So far I have:
* Figma
* GitHub
* Amazon Cognito
* Cronofy
