### ISSUE TITLE
Goals: October 2023

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#616]
By 10/31/23

#### Final reviews:
- [ ] Coordinator Dashboard #501
- [ ] Guest Application #533 

#### New Items:
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Guest Profile #589

#### In progress:

- [ ] Coordinator invite guests #405
- [ ] Guest Account Confirmation #440
- [ ] Guest Dashboard endpoints - needs data/infra structure solidifying
- [ ] API authentication (cognito + IAM)
- [ ] Coordinator dashboard

#### New Items:

- [x] Application Signature research #611

### PM:
- [x] Application Signature research #611
- [x] Host profile
- [ ] Matching epic

**Comment by rpradheap** [comment]
Notes from 10/17 Meeting

-PM and Design Team to finalize Guest and Coordinator flows
-Host Flows are yet to be started
-Eric is almost done with https://github.com/hackforla/HomeUniteUs/issues/405 and https://github.com/hackforla/HomeUniteUs/issues/440
-Joshua is working on Data Modeling/Infrastructure and it make take few weeks to finalize. API Authentication is in progress.
-Eric is working on coordinator Dashboard. Desktop version is almost done . There are some layout issues with mobile flow that Eric is working on.

Application Signature research - As a team we decided to have a checkbox with a legal language and box to type in the name as signature. Legal/ consent  wordings to be finalized by PM Team

**Comment by sanya301** [comment]
By 10/31/23

### Design:

#### Final reviews:
- Coordinator Dashboard #501 - PM input needed
- Guest Application #533 - ed working on this

### Eng:

#### In progress:

- API authentication (cognito + IAM) - another week or two out
- Coordinator invite guests + Guest Account Confirmation - just a couple of tests 
- Guest Dashboard endpoints - needs data/infra structure solidifying
- Coordinator dashboard 
- Application Signature research #611 - just a checkbox and text box for now, confirm with Raji

### PM:
- Application Signature research - confirm with bonnie
- Host profile - has been created
- Matching epic

**Comment by sanya301** [comment]
Notes from 10/24/23

### Design:

#### Final reviews:
- Coordinator Dashboard #501 - PM input needed
- Guest Application #533 - no updates, ed working on this, reach out to him

### Eng:

#### In progress:

- API authentication (cognito + IAM) - found some issue with session cookies, need more info on whether this will be handled separately or as a part of this story
- Coordinator invite guests + Guest Account Confirmation - no updates
- Guest Dashboard endpoints - no updates
- Coordinator dashboard - no updates
- Application Signature research #611 - just a checkbox and text box for now, confirm with Raji
- Incubator: Devops cloud environment - unsure if this needs to be part of MVP

### PM:
- Application Signature research - confirmed with bonnie
- Host profile - has been created
- Matching epic
