### ISSUE TITLE
January Goals

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#642]
By 01/31/24

#### Final reviews:
- [x] Coordinator Dashboard #501
- [ ] Guest Application #533 

#### New Items:
- [ ] Finalize Sidebar + top navigation
- [ ] Guest Profile #589
- [ ] Host Dashboard #508 
- [ ] Host Application #509 

#### In progress:

- [x] Coordinator invite guests #405
- [x] Guest Account Confirmation #440
- [ ] Guest Dashboard endpoints - needs data/infra structure solidifying
- [x] API authentication (cognito + IAM)
- [ ] Coordinator dashboard

### PM:
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Coordinator Application review page
- [ ] Coordinator User story for comments 
- [ ] Matching epic
- [ ] Just MVP user flow

**Comment by sanya301** [comment]
1/23/2024

### Design:

#### Final reviews:
- [ ] Coordinator Dashboard #501 - done, has been handed off to dev
- [ ] Guest Application #533 - Navigation sidebar mobile vs desktop review today - [ ] Finalize Sidebar + top navigation

#### New Items: can pick one up
- [ ] Guest Profile #589 
- [ ] Host Dashboard #508 
- [ ] Host Application #509 

### Eng:

#### In progress:

- [ ] Coordinator invite guests #405 - PR just needs to get merged in
- [ ] Guest Account Confirmation #440 - PR just needs to get merged in
- [ ] Guest Dashboard endpoints - needs data/infra structure solidifying
- [ ] API authentication (cognito + IAM) - put up a PR, in review. Cognito is mostly completed, just putting in configs for cognito user pools. Sign in, sign up is done. 
- [ ] Coordinator dashboard - some early development
- [ ] Guest application - stepper functionality, controlling flow through form, early forms 

### PM:
- [ ] Create Guest, Host and Coordinator Sidebar stories - working with design
- [ ] Coordinator Application review page - @rpradheap can you provide offline update
- [ ] Coordinator User story for comments  - @rpradheap can you provide offline update
- [ ] Matching epic - working on algo
- [ ] Just MVP user flow

**Comment by sanya301** [comment]
### Design:

#### Final reviews:
- [ ] Guest Application #533 - finalizing navigation

#### In Progress:
- [ ] Guest Profile #589 - has been started, questions for PM
- [ ] Host Dashboard #508 - in progress
- [ ] Host Application #509 - in progress

### Eng:

#### In progress:

- [ ] Coordinator invite guests #405 - done 
- [ ] Guest Account Confirmation #440 - done
- [ ] Guest Dashboard endpoints - design document in progress, open questions
- [ ] API authentication (cognito + IAM) - added infra to mock things in the application, unit tests for API. Comments to address
- [ ] Coordinator dashboard - discussion, scope
- [ ]  Guest application - stepper functionality, controlling flow through form, early forms

### PM:
- [ ] Create Guest, Host and Coordinator Sidebar stories - in progress
- [ ] Coordinator Application review page - follow up offline
- [ ] Coordinator User story for comments  - follow up offline
- [ ] Matching epic - working on algorithm
- [ ] Just MVP user flow
