### ISSUE TITLE
February 2024 goals

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#653]
By 02/29/24

#### Final reviews:
- [ ] Guest Application #533 
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Coordinator dashboard updates
- [ ] Guest dashboard - update text for guest profile and updates needed
- [ ] Desktop navigation

#### New Items:
- [ ] Guest Profile #589
- [ ] Finalize navigation
- [ ] Coordinator Application + Profile Review page
- [ ] Create a Figma demo for guest section 1 + 2

#### In progress:

- [ ] Guest Dashboard endpoints - needs data/infra structure solidifying
- [ ] Coordinator dashboard
- [ ] Confirm signature user story with PM - this is just going to be just an acknowledgement during signup
- [ ] AWS move to Incubator
- [ ] First name last name fix in sign up 

#### New Items:
- [ ] Design Application data models and outline endpoints #636
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add first name last name to sign up process

### PM:
- [ ] Coordinator Dashboard updates: confirm unused UI components, profile review navigation, add status prior to submission
- [ ] Coordinator Application review page
- [ ] Coordinator User story for comments 
- [ ] Matching epic: finalize algorithm, matching view page
- [ ] Guest profile view for host 
- [ ] Create Guest, Host and Coordinator Sidebar stories

**Comment by sanya301** [comment]
Eng:
In progress:
 [ ] Guest Dashboard endpoints - needs data/infra structure solidifying
 [ ] Coordinator dashboard
 [ ] Confirm signature user story with PM
 [ ] Move from personal AWS to incubator environment - went to ops meeting
New Items:
 [ ] Design Application data models and outline endpoints https://github.com/hackforla/HomeUniteUs/issues/636
 [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
 [ ] Coordinator dashboard endpoint https://github.com/hackforla/HomeUniteUs/issues/651
 [ ] Add first name last name to sign up process

**Comment by sanya301** [comment]
02/20/24

### Design:

#### Final reviews:
- [ ] Guest Application #533 - notes updates from last time, will go over in meeting
- [ ] Host Dashboard #508 - go over notes, small changes
- [ ] Host Application #509 - same as guest, go over notes
- [ ] Coordinator dashboard updates - small changes to look at
- [ ] Guest dashboard - notes updates from last time, will go over in meeting
- [ ] Desktop navigation for application

#### New Items:
- [ ] Guest Profile #589 - will be merged with application, review today
- [ ] Coordinator Application + Profile Review page
- [ ] Create a Figma demo for guest section 1 + 2, need to check with Ed



### Eng:

#### In progress:

- [ ] Guest Dashboard endpoints - needs data/infra structure solidifying
- [ ] Coordinator dashboard
- [ ] Confirm signature user story with PM
- [ ] AWS move to Incubator
- [ ] First name last name fix in sign up 

#### New Items:
- [ ] Design Application data models and outline endpoints #636
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add first name last name to sign up process

### PM:
- [ ] Coordinator Dashboard updates: confirm unused UI components, profile review navigation, add status prior to submission
- [ ] Coordinator Application review page
- [ ] Coordinator User story for comments 
- [ ] Matching epic: finalize algorithm, matching view page
- [ ] Guest profile view for host 
- [ ] Create Guest, Host and Coordinator Sidebar stories

**Comment by sanya301** [comment]
By 02/29/24

### Design:

#### Final reviews:
- [ ] Guest Application #533 
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Coordinator dashboard updates
- [ ] Guest dashboard - update text for guest profile and updates needed
- [ ] Desktop navigation

#### New Items:
- [ ] Guest Profile #589
- [ ] Finalize navigation
- [ ] Coordinator Application + Profile Review page
- [ ] Create a Figma demo for guest section 1 + 2



### Eng:

#### In progress:
- [ ] Guest Dashboard endpoints - in progress
- [ ] Coordinator dashboard - no new updates
- [ ] Confirm signature user story with PM - this is just going to be just an acknowledgement during signup
- [ ] AWS move to Incubator
- [ ] First name last name fix in sign up - needs to get merged in
- [ ] HMIS update: HUD provides all specifications. Task on our side is that data that we capture is integrated with what HUD provides. Old solution (HSLynk) had client side, and server side @tylerthome @rpradheap 

#### New Items:
- [ ] Design Application data models and outline endpoints #636
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add first name last name to sign up process

### PM:
- [ ] Coordinator Dashboard updates: confirm unused UI components, profile review navigation, add status prior to submission
- [ ] Coordinator Application review page
- [ ] Coordinator User story for comments 
- [ ] Matching epic: finalize algorithm, matching view page
- [ ] Guest profile view for host 
- [ ] Create Guest, Host and Coordinator Sidebar stories
