### ISSUE TITLE
March 2024 goals

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#664]
By 03/30/24

#### Final reviews:
- [x] Guest Application/Profile #533 - **finalize saving functionality**
- [x] Guest dashboard - rename guest application to profile, add screen for in progress profile, update post submission screen to say that profile is waiting on coordinator review
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Desktop navigation
- [ ] Figma demo for guest section 1 + 2 - to show to Bonnie

#### New Items:
- [ ] Coordinator Application + Profile Review page
- [ ] Coordinator dashboard updates: add status prior to submission
- [ ] Guest/Host sign up: Add acknowledgement functionality
- [ ] Coordinator: View and Take action on Applications #517
- [ ] Coordinator: Assign and reassign applications #518

#### In progress:
- [ ] Guest Dashboard endpoints - continue data/infra structure solidifying
- [ ] Coordinator dashboard
- [ ] AWS move to Incubator
- [ ] First name last name fix in sign up
- [ ] HMIS: ensure data that we capture is integrated with what HUD provides. Work with 

#### New Items:
- [ ] Design Application data models and outline endpoints #636
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup

#### Final reviews:
- [x] Matching epic: finalize algorithm, matching view page

#### Awaiting review
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Guest application #533 + Profile #589 - finalize saving functionality

#### New:
- [ ] Guest/host sign up: add acknowledgement functionality #439
- [ ] Coordinator update meeting & interview attendance/status for guest/host
- [ ] Guest profile view for host 
- [ ] CCPA requirements
- [ ] Host Matching Profile view 
- [ ] Create Guest, Host and Coordinator Sidebar stories

**Comment by sanya301** [comment]
03/19/24

### Design:

#### Final reviews:
- [ ] Guest Application/Profile #533 - **finalize saving functionality**
- [ ] Guest dashboard - rename guest application to profile, add screen for in progress profile, update post submission screen to say that profile is waiting on coordinator review - finalize today
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Desktop navigation
- [ ] Figma demo for guest section 1 + 2 - to show to Bonnie - finalize mobile version tonight, after that desktop will be finalized

#### New Items:
- [ ] Coordinator Application + Profile Review page
- [ ] Coordinator dashboard updates: add status prior to submission
- [ ] Guest/Host sign up: Add acknowledgement functionality
- [ ] Coordinator: View and Take action on Applications #517
- [ ] Coordinator: Assign and reassign applications #518

### Eng:

#### In progress:
- [ ] Guest Dashboard endpoints - continue data/infra structure solidifying
- [ ] Coordinator dashboard
- [ ] Guest Dashboard endpoints + Coordinator dashboard: User roles PR is sent out: major data model update, done by this weekend
- [ ] AWS move to Incubator: more progress this week OIDC provider
- [ ] ~~First name last name fix in sign up~~
- [ ] HMIS: ensure data that we capture is integrated with what HUD provides. Sent PMs a doc on this. Question is still out on 3rd party to store the data @rpradheap to come back next week

#### New Items:
- [ ] Design Application data models and outline endpoints #636
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup

### PM:

#### Final reviews:
- [ ] Matching epic: finalize algorithm, matching view page

#### Awaiting review
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Guest application #533 + Profile #589 - finalize saving functionality

#### New:
- [ ] Guest/host sign up: add acknowledgement functionality #439
- [ ] Coordinator update meeting & interview attendance/status for guest/host
- [ ] Guest profile view for host 
- [ ] CCPA requirements
- [ ] Host Matching Profile view 
- [ ] Create Guest, Host and Coordinator Sidebar stories

**Comment by sanya301** [comment]
03/26/24

### Design: No design meeting this week

#### Final reviews:
- [ ] Guest Application/Profile #533 - **finalize saving functionality** updated based on last week
- [x] Guest dashboard - rename guest application to profile, add screen for in progress profile, update post submission screen to say that profile is waiting on coordinator review
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Desktop navigation
- [ ] Figma demo for guest section 1 + 2 - to show to Bonnie

#### New Items:
- [ ] Coordinator Application + Profile Review page
- [ ] Coordinator dashboard updates: add status prior to submission
- [ ] Guest/Host sign up: Add acknowledgement functionality
- [ ] Coordinator: View and Take action on Applications #517
- [ ] Coordinator: Assign and reassign applications #518

### Eng:

#### In progress:
- [ ] Guest Dashboard endpoints - continue data/infra structure solidifying
- [ ] AWS move to Incubator
- [ ] First name last name fix in sign up: close to being done, PR is up
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator'): close to being done, PR is up
- [ ] Coordinator dashboard: after above two are merged
- [ ] HMIS: ensure data that we capture is integrated with what HUD provides: waiting on bonnie, add tyler to meeting

#### New Items:
- [ ] Design Application data models and outline endpoints #636
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup

### PM:

#### Final reviews:
- [ ] Matching epic: finalize algorithm, matching view page

#### Awaiting review
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Guest application #533 + Profile #589 - finalize saving functionality

#### New:
- [ ] Guest/host sign up: add acknowledgement functionality #439
- [ ] Coordinator update meeting & interview attendance/status for guest/host
- [ ] Guest profile view for host 
- [ ] CCPA requirements
- [ ] Host Matching Profile view 
- [ ] Create Guest, Host and Coordinator Sidebar stories
