### ISSUE TITLE
April 2024 goals

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#673]
By 04/30/24

#### Final reviews:
- [x] Guest Dashboard labels final review
- [x] Figma demo for guest section 1 + 2 - to show to Bonnie
- [ ] Guest Application for Desktop
      - [ ] User testing
      - [ ] Add expand collapse - need to discuss in design
      - [ ] Page numbers: some way to know, how do we deal with minimum expectations
      - [ ] Text that specifies they can move around in the application without completing all the section
      - [x] Text to say that everything will be auto saved 
      - [ ] Move guest minimum expectations to sign up process
      - [x] Phone number flag
      - [ ] Place for contracts/agreements
      - [ ] Submit button placement on review page - user testing will let us know
      - [ ] Review button might not look like a button - user testing item
      - [ ] Decide on partial filled logo (post MVP)
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Desktop navigation

#### New Items:
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application 
- [ ] Coordinator notes: Save and cancel + editing screens for notes #519 
- [ ] Coordinator: Intake Profile Review page #635
- [ ] Coordinator: Assign and reassign applications #518
- [ ] Guest/Host sign up: Add acknowledgement functionality
- [ ] FAQ: after PM has written this

#### In progress:
- [ ] Guest Dashboard endpoints - continue data/infra structure solidifying #636
- [x] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard: HTTP integrations and major panels complete with populated data
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024)
- [ ] First name last name fix in sign up - pending further discussion on Google first/last name #680
- [ ] HMIS: ensure data that we capture is integrated with what HUD provides. Work with PMs

#### New Items:
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup
- [ ] Guest intake profile mobile 

#### Final reviews:
- [x] Matching epic: finalize algorithm, matching view page
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Guest application #533 + Profile #589 - finalize saving functionality
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application #656 needs to be merged into this. Also add matching profile link here @rpradheap 
- [x] Close the duplicate intake profile story #517
- [ ] Host Matching Profile view 

#### New:
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] FAQ user story
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
- [ ] Guest/host sign up: add acknowledgement functionality #439
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [x] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching

**Comment by sanya301** [comment]
# Notes 04/02/2024

## Eng
- Auditing requirement: why is x guest taking so long to match with a host. I think status here might hopefully be enough for this https://docs.google.com/document/d/1mksBNqE9hc-bAW49mdHQDImkk8f92YewtwENNpqvFHc/edit @tylerthome 
   - Confirm with Bonnie as to what level this might be needed

**Comment by sanya301** [comment]
4/9

### Design:

#### Final reviews:
- [ ] Guest Dashboard labels final review - today
- [ ] Figma demo for guest section 1 + 2 - to show to Bonnie - April 16 
- [ ] Guest Application for Desktop - started

### Eng:

#### In progress:
- [ ] Guest Dashboard endpoints - continue data/infra structure solidifying #636
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator')
- [ ] Coordinator dashboard: HTTP integrations and major panels complete with populated data
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024)
- [ ] First name last name fix in sign up - pending further discussion on Google first/last name
- [ ] HMIS: ensure data that we capture is integrated with what HUD provides. Work with PMs

#### New Items:
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup
- [ ] Guest intake profile mobile 

### PM:

#### Final reviews:
- [ ] Matching epic: finalize algorithm, matching view page
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Guest application #533 + Profile #589 - finalize saving functionality
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application #656 needs to be merged into this. Also add matching profile link here @rpradheap 
- [ ] Close the duplicate intake profile story #517
- [ ] Host Matching Profile view 


#### New:
- [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] Guest/host sign up: add acknowledgement functionality #439
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [ ] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Host experience for matching

**Comment by sanya301** [comment]
By 04/30/24

### Design:

#### Final reviews:
- [x] Guest Dashboard labels final review - complete
- [x] Figma demo for guest section 1 + 2 - to show to Bonnie
- [ ] Guest Application for Desktop/mobile - guest minimum expectations, page numbers, decide on partial filled logo, text that specifies they can move around in the application without completing all the section
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Desktop navigation
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application - working on the design

### Eng:

#### In progress:
- [ ] Database design for intake profile - looking good
- [ ] Guest Dashboard endpoints - continue data/infra structure solidifying #636 - planning done, will get started on
- [ ] Assign user roles (eg. 'Guest', 'Host', 'Coordinator'), PR merged in
- [ ] Coordinator dashboard: No updates here
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024) - been making updates to this
- [ ] First name last name fix in sign up - pending further discussion on Google first/last name: we're ok to use Google single sign on
- [ ] HMIS: post MVP

### PM:

#### Final reviews:
- [x] Matching epic: finalize algorithm, matching view page
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Guest application #533 + Profile #589 - finalize saving functionality
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application #656 needs to be merged into this. Also add matching profile link here @rpradheap 
- [ ] Close the duplicate intake profile story #517
- [ ] Host Matching Profile view 


#### New:
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
- [ ] Guest/host sign up: add acknowledgement functionality #439
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [ ] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching

**Comment by sanya301** [comment]
By 04/30/24

### Design:

#### Final reviews:
- [ ] Guest Application for Desktop
      - User testing down the line
      - FAQ: added this
      - Page numbers: some way to know - need to discuss
      - Text that specifies they can move around in the application without completing all the sections - added but need to review
      - [x] Phone number flag - removed
      - Place for contracts/agreements - going to be under documents, need to review
      - Submit button placement on review page - discuss with PMs
      - Review button might not look like a button - minor but take 
      - Decide on partial filled logo (post MVP) - changed color to blue for accessibility
- Coordinator dashboard: adjusted components for design system
     - Questions from prev design 

### Eng:

#### In progress:
- Coordinator dashboard: Loading state design changes
- Incubator: hope to get done in next week 
- First name last name fix in sign up, Google - PR up 85% of the way. Some issues b/w sign up vs sign in with google
- Guest intake profile: both front end and back end at the same time going on. This set up would be general to any application


### PM:

#### Final reviews:
- [x] Matching epic: finalize algorithm, matching view page

**Comment by sanya301** [comment]
Feedback from Bonnie @edela0015 
Guest Dashboard+ Application for Desktop
- User testing down the line
- FAQ: added this
- Page numbers: some way to know
- Text that specifies they can move around in the application without completing all the sections 
-  Phone number flag 
- Place for contracts/agreements 
- Submit button placement on review page
- Review button might not look like a button
- Decide on partial filled logo (post MVP)

**Comment by sanya301** [comment]
Also need to discuss
- Minimizing menu for desktop Intake profile

**Comment by sanya301** [comment]
By 04/30/24

### Design:

#### Final reviews:
- Coordinator figma has a lot of comments that are being reviewed currently
- Guest 1c not completed yet, account confirmation - add sign up to this
- Looking at tools for user testing - check with design community of practice

#### New Items:
- Need to add Guest minimum expectations

### Eng:

#### In progress:
- First name last name fix in sign up - #680 tried an approach but blocked
- Guest Dashboard endpoints - continue data/infra structure solidifying #636 in progress
- Coordinator dashboard: HTTP integrations and major panels complete with populated data
   - Loading state completed #669
- Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024) - need to create one @tylerthome and add here
   - Went to ops meeting last week, will be helping them as there are some things breaking

### PM:

#### Final reviews:
- [x] Matching epic: finalize algorithm, matching view page
- [ ] Coordinator User stories: Application review page, comments, notes etc - in progress
- [x] Guest application #533 + Profile #589 - finalize saving functionality
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application #656 needs to be merged into this. Also add matching profile link here @rpradheap 
- [x] Close the duplicate intake profile story #517
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
  

#### New:
- [ ] Guest/host sign up: add acknowledgement functionality #439 - initial notes on this
- [ ] Host Matching Profile view 
- [ ] FAQ user story
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [ ] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching
