### ISSUE TITLE
May 2024 Goals

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#689]
By 05/31/24

#### Final reviews:
- [x] Guest Application for Desktop (pre usability testing): 
    - [x] Page numbers: some way to know, how do we deal with minimum expectations
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] #440 
    - [ ] Pending acknowledgement functionality - Prototype for user testing in progress, some complexity noted
    - [ ] Analysis and study anticipated to complete June 30th 

#### New Items:
- [ ] Guest/Host sign up: Add acknowledgement functionality
- [ ] Guest application: User testing: 
    - [ ] Research plan
    - [ ] Review button might not look like a button
    - [ ] Add expand collapse for Application sections in desktop
    - [ ] Submit button placement on review page
    - [ ] Text that specifies they can move around in the application without completing all the sections
- [ ] Move guest minimum expectations to sign up process
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application 
- [ ] Coordinator notes: Save and cancel + editing screens for notes #519 
- [ ] Coordinator: Assign and reassign applications #518

#### In progress:
- [ ] All user roles sign in demo 
    - [x] First name last name fix in sign up - pending further discussion on Google first/last name #680
- [ ] Guest form endpoints #636
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024) #686
   - [ ] Anticipated migration May 31st (original completion date April 30th)
   - [ ] PR merged; credential accounts created to run deployment
   - [ ] Access granted to administer share AWS environment
   - [ ] Major dependency - Cognito to support user management
- [ ] Guest dashboard #572 #566
     - No one is currently working on #572

#### New Items:
- [ ] Coordinator invite guest 
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup
- [ ] Guest intake profile mobile 

#### Final reviews:
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Host Matching Profile view 
- [ ] Guest/host sign up: add acknowledgement functionality #439

#### New:
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] FAQ user story
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [x] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching
- [ ] Downloadable intake profile instead of email
- [ ] Log of when guest and host worked on the app: V2

**Comment by sanya301** [comment]
06/04

### Design:

#### Final reviews:
- [x] Guest Application for Desktop: 
      - [x] Page numbers
      - [x] Text that specifies they can move around in the application without completing all the section
- [ ] Host Dashboard #508 - will be picked up next, waiting on PM
- [ ] Host Application #509  - will be picked up next, waiting on PM
- [ ] #440 
   - [ ] Pending acknowledgement functionality - Prototype for user testing in progress, some complexity noted
   - [ ] Analysis and study anticipated to complete June 30th 

#### New Items:
- [ ] Guest/Host sign up: Add acknowledgement functionality - need to double check
- [ ] Move guest minimum expectations to sign up process - need to double check
- [ ] Guest application: User testing: 
         - [ ] Research plan - finalizing plan, working on figma prototype
         - [ ] Review button might not look like a button
         - [ ] Add expand collapse for Application sections in desktop
         - [ ] Submit button placement on review page
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application 
    - [ ] Filter is complete, need to discuss but ready for review
- [ ] Coordinator notes: Save and cancel + editing screens for notes #519 - discuss today but ready for review
- [ ] Coordinator: Assign and reassign applications, filter #518 - need to discuss but ready for review
     - [ ] Bia to synch up with Mira on the features and clarify what/which team is working on this (Eng or Design)

### Eng:

#### In progress:
- [ ] All user roles sign in demo 
    - [ ] First name last name fix in sign up - pending further discussion on Google first/last name #680
        - [ ] Original issue requirements met and should be closed.  This will be replaced with the linking issue, once the issue is created.
- [ ] Guest form endpoints #636
    - [ ] Josh to complete and roll off project
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024) #686
   - [ ] Anticipated migration May 31st (original completion date April 30th)
   - [ ] PR merged; credential accounts created to run deployment
   - [ ] Access granted to administer share AWS environment
   - [ ] Major dependency - Cognito to support user management
- [ ] Guest dashboard #572 #566
     - No one is currently working on #572

#### New Items:
- [ ] Coordinator invite guest 
     - Anything else to view?
     - What's the protocol to close out? 
         - PM to view and provide feedback and then close out?
- [ ] Coordinator dashboard endpoint #651 
     - Hold off - Not currently worked on
- [ ] Add acknowledgement during signup
- [ ] Guest intake profile mobile 

### PM:

#### Final reviews:
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Host Matching Profile view 
- [ ] Guest/host sign up: add acknowledgement functionality #439


#### New:
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] FAQ user story
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [x] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching
- [ ] Downloadable intake profile instead of email
- [ ] Log of when guest and host worked on the app: V2

**Comment by sanya301** [comment]
Notes from 5/21 I assume 

By 05/31/24

### Design:

#### Final reviews:
- [x] Guest Application for Desktop (pre usability testing): 
    - [x] Page numbers: some way to know, how do we deal with minimum expectations
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] #440 
    - [ ] Pending acknowledgement functionality - Prototype for user testing in progress, some complexity noted
    - [ ] Analysis and study anticipated to complete June 30th 

#### New Items:
- [ ] Guest/Host sign up: Add acknowledgement functionality
- [ ] Guest application: User testing: 
    - [ ] Research plan
    - [ ] Review button might not look like a button
    - [ ] Add expand collapse for Application sections in desktop
    - [ ] Submit button placement on review page
    - [ ] Text that specifies they can move around in the application without completing all the sections
- [ ] Move guest minimum expectations to sign up process
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application 
- [ ] Coordinator notes: Save and cancel + editing screens for notes #519 
- [ ] Coordinator: Assign and reassign applications #518

### Eng:

#### In progress:
- [ ] All user roles sign in demo 
    - [x] First name last name fix in sign up - pending further discussion on Google first/last name #680
        - [ ] Original issue requirements met and should be closed.  This will be replaced with the linking issue, once the issue is created.
- [ ] Guest form endpoints #636
    - [ ] Josh to complete and roll off project
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024) #686
   - [ ] Anticipated migration May 31st (original completion date April 30th)
   - [ ] PR merged; credential accounts created to run deployment
   - [ ] Access granted to administer share AWS environment
   - [ ] Major dependency - Cognito to support user management
- [ ] Guest dashboard #572 #566
     - No one is currently working on #572

#### New Items:
- [ ] Coordinator invite guest 
     - Anything else to view?
     - What's the protocol to close out? 
         - PM to view and provide feedback and then close out?
- [ ] Coordinator dashboard endpoint #651 
     - Hold off - Not currently worked on
- [ ] Add acknowledgement during signup
- [ ] Guest intake profile mobile 

### PM:

#### Final reviews:
- [ ] Coordinator User stories: Application review page, comments, notes etc
- [ ] Host Matching Profile view 
- [ ] Guest/host sign up: add acknowledgement functionality #439


#### New:
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] FAQ user story
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [x] CCPA requirements: update on what needs 
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching
- [ ] Downloadable intake profile instead of email
- [ ] Log of when guest and host worked on the app: V2
