### ISSUE TITLE
HUU: PM Agenda and Meeting Minutes 2024

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#692]
### Overview
This issue tracks the agenda for the PM meetings for the HomeUniteUS project

### Resources
Add a link to each comment below (each one being an agenda and meeting minutes
## Preparation for Meeting: PMs
- [ ] #[INSERT UPDATE TEAM ROSTER AND ISSUE ASSIGNMENT ISSUE NUMBER] and offboard if needed
- [ ] #[INSERT WEEKLY LABEL CHECK ISSUE NUMBER]  
- [ ] #[INSERT ICEBOX REVIEW ISSUE NUMBER]
- [ ] Make sure that all issues in the New Issue Review/Approval column either have: 
    - [ ] A `ready for...` label [INSERT URL FOR PROJECT BOARD FILTERED FOR `status:"New Issue..."` column AND `-label:"ready for..."`for each 'ready for' label]. If this link contains any issues, they need to be given the appropriate "ready for..." label or...
    - [ ] A `draft` label and the author/someone assigned to them
- [ ] Make sure that all items in the Questions/Review column have a `ready for...` label [INSERT URL FOR PROJECT BOARD FILTERED FOR `status:"Questions..."` column AND `-label:"ready for..."`for each 'ready for' label]. If this link contains any issues, they need to be given the appropriate `ready for...` label.
- [ ] Review the issues with the following labels on the whole project board and either address them now or add to this agenda to discuss.
   - [ ] `Ready for Product` [INSERT URL FOR PROJECT BOARD FILTERED FOR `label:"ready for product"`]
   - [ ] `Ready for Prioritization`[INSERT URL FOR PROJECT BOARD FILTERED FOR `label:"ready for prioritization"`]
- [ ] Check for new issues in the Questions/Review column. Add a link to the question-asking comment from each new issue to the the agenda below

### Minutes Template
```
# 2024-05-15 PM Agenda and Minutes 

## Prework

- [ ] label audit #354 

For example, see https://github.com/hackforla/peopledepot/issues/461

## Roll Call
  - [ ] Gabriella Dominic
  - [ ] Jasmine Guraya
  - [ ] Jasika Kalra
  - [ ] London Kim
  - [ ] Sanju Venugopal 
  - [ ] Aisha Uqdah
  - [ ] Suyen Stevenson
  - [ ] Lola Sarumi

## Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/62/views/1?filterQuery=new+issue+approval)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## New Items and Items from Previous Meeting

## Actions taken or notes about stuff from the meeting:

## New Task Items
```

**Comment by sanya301** [comment]
Placeholder for prior agendas

**Comment by sanya301** [comment]
# 2024 05 09 PM Meeting Notes

## Agenda:
- #501 - reviewed, need to just review 
- Question: PDF vs in app review for coordinator

## Next steps:
- [ ] Coordinator stories    
    - [ ] #635 - second priority, need to rethink wording as this is no longer just a review application page if we are changing dashboard
    - [ ] #518 
    - [ ] #519 - needs to remove association with "applications" as notes go beyond applications
    - [ ] #520
    - [ ] #519 
    - [ ] #518 
    - [ ] #635
    - [ ] Review #501 - super important. 
        - [ ] Add status prior to submission. 
        - [ ] Add a column to have link to application #656 needs to be merged into this. 
        - [ ] Also add matching profile link here
    - [ ] Close the duplicate intake profile story #517
    - [ ] #635
    - [ ] https://github.com/hackforla/HomeUniteUs/issues/created_by/rpradheap
    - [ ] Review #454, #656 @rpradheap, please add labels and list new stories in Coordinator epic

**Comment by sanya301** [comment]
## 2024-05-16 PM Agenda and Minutes 

### Roll Call

- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya

#### Recurring items proposal for future meetings: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel]()
       - [ ] [Jasika]()
       - [ ] [Lola]()
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

#### New Items and Items from Previous Meeting
- https://github.com/hackforla/HomeUniteUs/issues/635
- https://github.com/hackforla/HomeUniteUs/issues/520

#### Actions taken or notes about stuff from the meeting:

#### New Task Items

**Comment by lasryariel** [comment]
# 2024-05-23 PM Agenda and Minutes 

## Roll Call

- [x] Ariel
- [ ] Jasika
- [x] Lola
- [] Sanya

## Recurring items proposal for future meetings: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## New Items and Items from Previous Meeting
- https://github.com/hackforla/HomeUniteUs/issues/635
- https://github.com/hackforla/HomeUniteUs/issues/520

## Actions taken or notes about stuff from the meeting:

## New Task Items

**Comment by lasryariel** [comment]
# 2024-05-30 PM Agenda and Minutes 

## Roll Call

- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya

## Recurring items proposal for future meetings: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## New Items and Items from Previous Meeting
- https://github.com/hackforla/HomeUniteUs/issues/635
- https://github.com/hackforla/HomeUniteUs/issues/520

## Actions taken or notes about stuff from the meeting:

## New Task Items
- [ ] Ariel: Github Projects Classic will be sunset, Bonnie said we will only be migrating one board, so we need to discuss if we need anything from the User Story Project: https://github.com/hackforla/HomeUniteUs/projects/6

**Comment by lasryariel** [comment]
# 2024-06-06 PM Agenda and Minutes 

## Roll Call

- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya

## Recurring items proposal for future meetings: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues [labeled "Ready for: Product"](https://github.com/hackforla/HomeUniteUs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Ready+for%3A+Product%22)

## New Items and Items from Previous Meeting
- https://github.com/hackforla/HomeUniteUs/issues/635
- https://github.com/hackforla/HomeUniteUs/issues/520

## Actions taken or notes about stuff from the meeting:

## New Task Items
- [x] Ariel: Github Projects Classic will be sunset, Bonnie said we will only be migrating one board, so we need to discuss if we need anything from the User Story Project: https://github.com/hackforla/HomeUniteUs/projects/6 - we ended up saving everything to a [spreadsheet](https://docs.google.com/spreadsheets/d/1HQaVLankcDA8qEBFfl35VqB9WQpWynK12ICdd_NhDdI/edit?usp=drive_link)

**Comment by sanya301** [comment]
# 2024-06-06 PM Agenda and Minutes 

## Prework
- [ ] label audit #354

## Roll Call

- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya

## Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel]()
       - [ ] [Jasika]()
       - [ ] [Lola]()
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## New Items and Items from Previous Meeting

## Actions taken or notes about stuff from the meeting:

## New Task Items

**Comment by sanya301** [comment]
# 2024-06-11 PM Agenda and Minutes 

## Prework
- [ ] label audit #354

## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya

## Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## New Items and Items from Previous Meeting
- Discussed project board cleanup
- Discussed better collaboration with Engineering

## Actions taken or notes about stuff from the meeting:

## New Task Items

- Coordinator epic (user journey) needs to be updated and presented to the design team. Define by end of this section, coordinator needs to do this @lasryariel 
- @lasryariel update filter user story to define name filter requirements if any, and use cases for search bar
- Create a listing for a user researcher? @edela0015 
- Check with engineering on acknowledgement placement

**Comment by sanya301** [comment]
# 2024-06-20 PM Agenda and Minutes 

## Prework
- [ ] label audit #354

## Roll Call
- [x] Ariel
- [x] Jasika
- [ ] Lola
- [x] Sanya

## Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## New Items and Items from Previous Meeting
- Filter user story review: @lasryariel update filter user story to define name filter requirements if any, and use cases for search bar
- Host dashboard review
- Coordinator epic review?

## Actions taken or notes about stuff from the meeting:

## New Task Items
- [ ] Coordinator epic (user journey) needs to be updated and presented to the design team. Define by end of this section, coordinator needs to do this 
- [ ] Create a listing for a user researcher?

**Comment by lasryariel** [comment]
# 2024-06-27 PM Agenda and Minutes 

## Prework
- [ ] label audit #354

## Roll Call
- [x] Ariel
- [x] Jasika
- [x] Lola
- [x] Sanya

## Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/62/views/1?filterQuery=new+issue+approval)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [ ] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

## Actions taken or notes about stuff from the meeting:
- Acceptance criteria for invite guest #520 reviewed
- User interview demo https://participate.lookback.io/qNqfbB?preview
- Next week @lasryariel create agenda for both team (host this) and PM meeting

## New Task Items
- [ ] Filter user story review: @lasryariel update filter user story to define name filter requirements if any, and use cases for search bar
- [ ] Host dashboard review
- [ ] Coordinator epic (user journey) needs to be updated and presented to the design team. Define by end of this section, coordinator needs to do this 
- [ ] Create a listing for a user researcher?

**Comment by lola3736** [comment]
# 2024-08-07 PM Agenda and Minutes 

## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya
- [ ] Gaberiella
- [ ] Teja
- [ ] Essence

## Prework
- [x] label audit #354

## Team Introduction
- [ ] New team members
- [ ] Onboarding

## Recurring items - Project Board Cleanup: 
- [ ] 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/62/views/1?filterQuery=new+issue+approval)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [x] [Ariel](https://github.com/hackforla/HomeUniteUs/issues/assigned/lasryariel)
       - [x] [Jasika](https://github.com/hackforla/HomeUniteUs/issues/assigned/jasika-ai)
          - [ ] Make sure all stories are labeled "Ready for ..." or be In Progress
          - [ ] Double check that any matching questions in the open questions google doc have been accounted for
       - [ ] [Lola](https://github.com/hackforla/HomeUniteUs/issues/assigned/lola3736)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)

## Actions taken or notes about stuff from the meeting:
- [x] Create a listing for a user researcher? 
   - [x] Ariel: Another Designer and Back End dev are needed too. Is that PM responsibility? 
      - Discussed role posting responsibilities
         - historically Sanya has posted roles, not sure what the official policy for hackforla is (could confirm with Bonnie)
         - We do need work documented as issues before we post a role, so at least for research role we need Ed to work through what they will be doing and create issues.
- [x] Discuss Background Checks requirement for each persona
   - For MVP background check in HUU or Guest/Host is just informing them that the background check will happen (already implemented)/has been completed
   - For Coordinator they will just have the ability to confirm that the background check was completed successfully or not

## New Task Items
- [x] Filter user story review: @lasryariel update filter user story to define name filter requirements if any, and use cases for search bar
   - [ ] Ariel: Done, needs review. 
- [x] Coordinator epic (user journey) needs to be updated and presented to the design team. Define by end of this section, coordinator needs to do this 
   - [ ] Ariel: Done, needs review
- [ ] Host dashboard review
- [ ] For next meeting (8/1) we can work on setting up August goals as a team, prepping for the Tuesday lead meeting to get feedback from Ed/Tyler
   - [ ] We will use[ this timeline](https://docs.google.com/spreadsheets/d/1LSdAry5I3ktpeqUjajCCq4STDg0XSmRBtxVfUADFk9A/edit?gid=0#gid=0) for the leads meeting
- [x] Cancel the meetings for July so they aren't on everyone's calendar? - Sanya will do this
- [ ] Ariel: would it be helpful if we hid comments as we went for the recurring threads? Scrolling all the way down is a pain, and it's easy to accidentally edit the wrong one, and they can still be unhidden when needed. - Ariel will do this
- [ ] Check in before we come back with break to make sure roles were created before onboarding

**Comment by lola3736** [comment]
# 2024-08-15 PM Agenda and Minutes 

## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya
- [ ] Gaberiella
- [ ] Teja
- [ ] Jasmine

## Onboarding
- [ ] Add to Google calendar invites
  - [ ] Friday Meeting - PM Community of Practice 
- [ ] Confirm Figma Access

## Persona Assignment
- Coordinator 
   - Ariel (PM lead)
   - TBD (PM)
- Guest 
   - Jasika (PM Lead)
   - TBD (PM)
- Host 
   - Jasmine (PM Lead)
   - TBD (PM)

## Project Board Cleanup
 - [ ] Project Review and Management https://docs.google.com/spreadsheets/d/1LSdAry5I3ktpeqUjajCCq4STDg0XSmRBtxVfUADFk9A/edit?gid=0#gid=0
    - [ ] Prioritized Backlog (2)
      - [ ] #528 
      - [ ] #475 
   - [ ] New / Issue Approval (15)
      - [ ] #456 
      - [ ] #338 
      - [ ] #617 
      - [ ] #433 
      - [ ] #611 
      - [ ] #604
      - [ ] #380 
      - [ ] #416 
      - [ ] #418 
      - [ ] #305 
      - [ ] #3 
      - [ ] #737 
      - [ ] #315 
      - [ ] #618 
      - [ ] #432

**Comment by lola3736** [comment]
# 2024-08-22 PM Agenda and Minutes 
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya
- [ ] Gaberiella
- [ ] Teja
- [ ] Jasmine

## Recurring Items
### Workflow Review - Status
#### Section 1: Account Creation 
 - [ ] Coordinator
 - [ ] Guest 
 - [ ] Host
#### Section 2: Application and Onboarding Process
 - [ ] Coordinator
 - [ ] Guest 
 - [ ] Host
## Miscellaneous
- Persona Assignment
- Coordinator 
   - Ariel (PM lead)
   - Gaberiella (PM)
- Guest 
   - Jasika (PM Lead)
   - Teja (PM)
- Host 
   - Jasmine (PM Lead)
   - TBD (PM)

**Comment by lola3736** [comment]
# 2024-09-12 PM Agenda and Minutes 
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya
- [ ] Gaberiella
- [ ] Teja
- [ ] Jasmine

## Recurring Items
### Workflow Review - Status
#### Persona Breakout Session
##### Section 2: Application and Onboarding Process
 - Coordinator
 - Guest 
 - Host
## Miscellaneous
- Persona Assignment
- Coordinator 
   - Ariel (PM lead)
   - Gaberiella (PM)
- Guest 
   - Jasika (PM Lead)
   - Teja (PM)
- Host 
   - Jasmine (PM Lead)
   - Teja (PM)

**Comment by lola3736** [comment]
# 2024-10-03 PM Agenda and Notes 
## Recurring Items
- [ ] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)
- [ ] Round Table - Team update and question
  - [ ] [Status of Features Documentation](https://docs.google.com/spreadsheets/d/1uM287TOz20jnXPS4kRe0Dt5GlhnPbNRYBHHOxcamCJ0/edit?gid=0#gid=0)
  - [ ] [Coordinator - Need to add Admin Coordinator](https://docs.google.com/spreadsheets/d/1wJg1u7pBLRaiuebMPzkg-juLu3RRspEegRYlkE3LBx8/edit?gid=0#gid=0) 
  - [ ] [HUU Project is based on PSY Handbook version 1 ](https://drive.google.com/drive/u/1/folders/1Dj8qQfsHY4Meu6BTNYsGeUNWd_x1iaW0)
#### Persona Breakout Session
 - Coordinator
 - Guest 
 - Host
## Summary Meeting Notes
---
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya (Advisory)
- [ ] Gaberiella
- [ ] Teja
- [ ] Jasmine

**Comment by lola3736** [comment]
# 2024-10-10 PM Agenda and Notes 
## Recurring Items
- [ ] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)
- [ ] Round Table - Team update and question
  - [ ] [Status of Features Documentation](https://docs.google.com/spreadsheets/d/1uM287TOz20jnXPS4kRe0Dt5GlhnPbNRYBHHOxcamCJ0/edit?gid=0#gid=0)
  - [ ] [October Goals Draft](https://github.com/hackforla/HomeUniteUs/issues/806)
  - [ ] [Product CoP Meeting - update status](https://github.com/hackforla/HomeUniteUs/issues/800)
#### Persona Breakout Session
 - Coordinator
 - Guest 
 - Host
## Summary Meeting Notes
---
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya (Advisory)
- [ ] Gaberiella
- [ ] Teja
- [ ] Jasmine

**Comment by lola3736** [comment]
# 2024-10-10 PM Agenda and Notes 
## Recurring Items
- [ ] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)
- [ ] Round Table - Team update and question
  - [ ] [Status of Features Documentation](https://docs.google.com/spreadsheets/d/1uM287TOz20jnXPS4kRe0Dt5GlhnPbNRYBHHOxcamCJ0/edit?gid=0#gid=0)
  - [x] [October Goals](https://github.com/hackforla/HomeUniteUs/issues/806)
  - [ ] [Product CoP Meeting - update status](https://github.com/hackforla/HomeUniteUs/issues/800)
#### Persona Breakout Session
 - Coordinator
 - Guest 
 - Host
## Summary Meeting Notes

## Status 
- Action from 2024-10-10 meeting
   - [ ] Ariel to update GitHub with new timeline tracking approach for coordinator work
   - [ ] Team members to estimate completion dates for current work
   - [ ] Update issue #800 with latest project status for COP meeting
   - [ ] Attend COP meeting tomorrow to potentially discuss project updates
   - [ ] Schedule team discussion to review account creation progress and plan next priorities
Action Items		
  - [ ] Follow up with Tejas on feature prioritization work, determine timeline for completion - Jasmine Guraya
  - [ ] Finalize setup of GitHub project tracking for current work - add milestones, issues with dates for PM stories, design work
Ariel Lasry
  - [ ] Update issue #800 for COP meeting - note no change from last week due to Priyanka's illness - Gabriella Dominic

## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya (Advisory)
- [ ] Gaberiella
- [ ] Teja
- [ ] Jasmine

**Comment by lola3736** [comment]
# 2024-10-24 PM Agenda and Notes 
## Recurring Items
- [ ] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)
- [ ] Round Table - Team update and question
  - [ ] [Status of Features Documentation](https://docs.google.com/spreadsheets/d/1uM287TOz20jnXPS4kRe0Dt5GlhnPbNRYBHHOxcamCJ0/edit?gid=0#gid=0)
  - [ ] [October Goals](https://github.com/hackforla/HomeUniteUs/issues/806)
  - [ ] [Product CoP Meeting - update status](https://github.com/hackforla/HomeUniteUs/issues/800)
#### Persona Breakout Session
 - Coordinator
 - Guest 
 - Host
## Summary Meeting Notes

## Status 
- Action item from PM CoP
  - [ ] [Create project and accomplishments Epic](https://github.com/hackforla/admin-accomplishments/issues/3) - Gabriella 
- Action from 2024-10-10 meeting
   - [ ] Team members to estimate completion dates for current work
   - [ ] Schedule team discussion to review account creation progress and plan next priorities
Action Items		
  - [ ] Follow up with Tejas on feature prioritization work, determine timeline for completion - Jasmine Guraya
  - [ ] Finalize setup of GitHub project tracking for current work - add milestones, issues with dates for PM stories, design work
Ariel Lasry
  
---
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya (Advisory)
- [ ] Gabriella
- [ ] Teja
- [ ] Jasmine

**Comment by lola3736** [comment]
# 2024-10-31 PM Agenda and Notes 
## Recurring Items
- [ ] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)
  - New Issue Approval (Ready for Product)
    - [ ] Ariel
     - [ ] #765
     - [ ] #763 
    - [ ] #617    
 - In Progress
   - [ ] #736 can we remove the label - Ariel

 - For Review/Feedback Needed
  - [ ] #508 whats the status? ready for design? assign accordingly - Jasmine, Teja
  - [ ] #509 whats the status? ready for design? assign accordingly - Jasmine, Teja  
  - [ ] # 761 is this closed? - Ariel
- Ice Box
  - [ ] #635 remove "ready for product" label - Ariel
  - [ ] #731 similar to the above
  - [ ] #779 status?
- Done

- Removed "Ready for Product"
  - [ ] #740  
  - [ ] #489 Status? 
  ---
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya (Advisory)
- [ ] Gabriella
- [ ] Teja
- [ ] Jasmine

**Comment by jasika-ai** [comment]
#617 is a Guest Persona story. I was under the impression @sm10949 or @jasmineg95 are working on it.

**Comment by lola3736** [comment]
# 2024-11-08 PM Agenda and Notes 
## Recurring Items
- [x] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)

---
## Roll Call
- [x] Ariel
- [ ] Jasika
- [x] Lola
- [ ] Sanya (Advisory)
- [ ] Gabriella
- [x] Teja
- [ ] Jasmine

**Comment by lola3736** [comment]
# 2024-11-14 PM Agenda and Notes 
- [ ] Project Board Cleanup - [Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)
- [ ] Coordinator team to seek provisional approval for engineering to proceed with work on structural build - Nov 26th
- [ ] Provide your research questions
---
## Roll Call
- [ ] Ariel
- [ ] Jasika
- [ ] Lola
- [ ] Sanya (Advisory)
- [ ] Gabriella
- [ ] Teja
- [ ] Jasmine

**Comment by lola3736** [comment]
# 2025-01-06 PM Agenda and Notes

**Comment by lola3736** [comment]
# 2025-01-16 PM Agenda and Minutes 

## Agenda
- Overview of Personas
- 2025 Goals
## Recurring items:

## Roll Call
  - [ ] Gabriella Dominic
  - [ ] Jasmine Guraya
  - [ ] Jasika Kalra
  - [ ] London Kim
  - [ ] Sanju Venugopal 
  - [ ] Aisha Uqdah
  - [ ] Suyen Stevenson
  - [ ] Lola Sarumi

## Summary Meeting Notes:

**Comment by lola3736** [comment]
# 2025-01-23 PM Agenda and Minutes 
### Topics
- Project Status

## Roll Call
  - [ ] Gabriella Dominic
  - [ ] Jasmine Guraya
  - [ ] Jasika Kalra
  - [ ] London Kim
  - [ ] Sanju Venugopal 
  - [ ] Aisha Uqdah
  - [ ] Suyen Stevenson
  - [ ] Lola Sarumi

**Comment by lola3736** [comment]
# 2025-01-30 PM Agenda and Minutes 
### Topics
- Project Status
## Summary Meeting Minutes
- Meeting Purpose
  - Discuss project progress, GitHub usage, and next steps for the Home Unite Us (HUU) project.
### Key Takeaways
- Teams need to improve documentation and structure for handoffs, using GitHub issues and templates
- Host/Guest intake profile development is behind Coordinator team progress; focus needed here
- Research questions should be added to GitHub issue #839 for easier tracking and discussion
- Potential for new engineering resources from Ariel's company to join the project
### Topics
 - Project Documentation and GitHub Usage
   - Teams encouraged to document work and decisions in GitHub issues
   - GitHub navigation and issue creation process discussed and demonstrated
   - Balance needed between structure and ease of use for volunteer contributors
   - Coordinator team praised for thorough documentation, especially Priyanka's contributions
- Research Process and Questions
  - New GitHub issue (#839) created for collecting research questions
  - Team members encouraged to add questions informally before using formal intake form
  - Discussion on making the research process less intimidating for volunteers
- Host/Guest Intake Profile Development
  - London to work closely with Julia (designer) on host intake profile
  - Team to review and update user story #508 for host intake
  - Tuesday breakout session planned to focus on host/guest profile development
- Team Structure and Progress
  - Coordinator team significantly ahead in development compared to host/guest teams
  - Need to sync host/guest development with overall project timeline
 - Potential New Resources
  - Ariel exploring possibility of bringing engineers from his company to the project
  - Could potentially add 4+ new engineers to accelerate development
- Next Steps and Prioritization
  - Teams to review and update their respective areas in the high-level Figma workflow
  - Thursday meeting to focus on building priorities and next steps for each team
  - London to create a design handoff issue for host intake profile work
- Next Steps
  - Add research questions to GitHub issue #839
  - Review and update user story #508 for host intake profile
  - Prepare for Tuesday breakout session focusing on host/guest profile development
  - Create design handoff issue for host intake profile (London)
  - Develop prioritization and next steps for each team before Thursday's meeting

## Roll Call
  - [x] Gabriella Dominic
  - [ ] Jasmine Guraya
  - [ ] Jasika Kalra
  - [x] London Kim
  - [x] Sanju Venugopal 
  - [x] Aisha Uqdah
  - [x] Lola Sarumi

**Comment by lola3736** [comment]
# 2025-02-06 PM Agenda and Minutes 
### Topics
- Project Status
## Summary Meeting Minutes
Meeting Purpose
Discuss research questions, prioritization of work, and onboarding for new team member Aisha.

Key Takeaways
Team needs to prioritize features for MVP, breaking down large components (e.g. dashboard) into specific actionable items

Research questions identified; team to complete research request form for top 3 questions

New process for design approval: team agreement, engineering feasibility check, then present to Bonnie

Aisha to focus on reading handbook and familiarizing with guest intake process

Topics
Prioritization and Work Breakdown
Create swimlane/journey map to visualize user touchpoints and work sequence

Break down large components (e.g. dashboard) into specific features (est. 12 for coordinator dashboard)

Use existing features list to identify MVP scope and prioritize accordingly

Set realistic timelines for each step (e.g. 2 weeks for user story writing, 1-2 months for design)

Design Review Process
Team agreement on design

Engineering feasibility check

Present to Bonnie with engineering input

Aim to avoid fixating on minor details (e.g. button placement)

Research Questions
Identified key questions around application status tracking, matching factors, and user experience

Team to complete research request form for top 3 questions

Will incorporate answers into user stories and feature prioritization

Onboarding for Aisha (New Team Member)
Focus on reading handbook to understand project context

Review host intake form (Issue #508) and find equivalent for guest

Familiarize with features list and intake form requirements

Will have more detailed discussion next week after handbook review

Design Team Updates
Michael to sync with Priyanka on previous work

Plan to hire experienced designer for coordinator experience

Encourage design team to propose creative solutions rather than just implementing PM suggestions

Next Steps
Lola to organize research questions into request form template

Team to complete research request form for top 3 questions

Gabriela and Sanju to review coordinator dashboard features and prioritize

Aisha to read handbook and review intake form documentation

Lola to find and share guest intake form equivalent for Aisha

Team to review features list and ensure alignment with MVP scope

Lola to start using action items in meeting notes for better tracking

**Comment by lola3736** [comment]
# 2025-02-13 PM Agenda and Minutes 
### Topics
- Project Status
- Research Questions
## Summary Meeting M

## Roll Call
  - [x] Gabriella Dominic
  - [ ] Ariel Lasry
  - [ ] Jasmine Guraya
  - [ ] Jasika Kalra
  - [x] London Kim
  - [x] Sanju Venugopal 
  - [x] Aisha Uqdah
  - [x] Lola Sarumi

**Comment by lola3736** [comment]
2024 PM Agenda and Meeting Minutes Closed.  See 2025 Agenda.
