### ISSUE TITLE
Clean up Project Board/Issues

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#704]
### Overview
We need to clean up our Project Board and Issues for clarity on what is being worked on and to prepare for the Github Projects Migration

#### Issues
- [ ] Check that all issues are formatted properly
   - If an Issue is not properly formatted, label should be "Draft". 
   - Proper Format should use "Blank Issue" template
- [x] Recruitment Issues: should be similar to On/Offboarding: need documentation for how to manage, here is a link to an example I think: https://github.com/hackforla/internship/issues/154

#### Milestones
- [x] Add a Milestone for Legal Compliance - completed by Ariel 5/31 
- [ ] Move anything that is not for MVP to Post-MVP
- [ ] Document Milestone Use in [Wiki](https://github.com/hackforla/HomeUniteUs/wiki/Project-Board-and-Issues#milestones)

#### Labels
- [x] Create the following labels "Ready for [Product, Research Lead, Design Lead, Development Lead]" completed by Ariel 5/31
   - start Using these labels for any issues that needs to be cleaned up before it is ready to be put into prioritized backlog
   - [x] For any [issues that are using "ready for" labels](https://github.com/hackforla/HomeUniteUs/issues?q=is%3Aopen+label%3A%22Ready+for+Design+Lead%22%2C%22Ready+for+Development+Lead%22%2C%22Ready+for+Product%22%2C%22Ready+for+Research+Lead%22) that have questions, move to "Blocked" column 
      - completed by Ariel 5/31. Note that we are using "For Review/Feedback Needed" instead of "Blocked" column
- [x] Add Complexity label based on github.com//hackforla/website/labels?q=complexity
   - Make smaller issues out of bigger ones to make easier complexity issues
   - Bonnie has this comment which outlines how developers will move their way up a complexity chain: https://github.com/hackforla/website/issues/4944#issuecomment-1992820039
- [x] Use these points labels as well as a guide: https://github.com/hackforla/website/labels?q=size
- [ ] If an Issue is not properly formatted, label should be "Draft". 
- [ ] Document Label Use in [Wiki](https://github.com/hackforla/HomeUniteUs/wiki/Project-Board-and-Issues#labels)

##### Roles
- [x] Create 2 new roles - 1 for design and 1 for research - completed by Ariel 5/31
   - [x] Split out UI/UX between those 2 roles [Issues](https://github.com/hackforla/HomeUniteUs/labels/Role%3A%20UI%2FUX)
- [ ] There should only be one role on any given issue
- [x] Document Roles Use in [Wiki](https://github.com/hackforla/HomeUniteUs/wiki/Project-Board-and-Issues#role)
 

#### Columns
- [x] Document Columns Use in [Wiki](https://github.com/hackforla/HomeUniteUs/wiki/Project-Board-and-Issues#columns)
##### Icebox:
- [x] All issues in icebox should have a dependency issue that is a blocker to let us know when the issue will come out of the icebox
- [x] Icebox Issues should not have an assignee - Completed by Ariel 5/31

**Comment by lasryariel** [comment]
Updated instructions are in #733 closing this issue to reduce duplication.
