### ISSUE TITLE
August 2024 Goals

### ISSUE THREAD

**Issue by lola3736** [hackforla/HomeUniteUs#733]
By 8/31/2024
# August Plan
### Recruiting
- [x] Recruit 2 PM's per Persona 
- [x] Recruit 2 designers per persona
- [x] Recruit Design Lead (Nicci)
- [x] Recruit Research Lead (Nicci) 
- [x] Recruit 3 Researchers
- [ ] Determine Engineering Team structure (possibly per persona)

### Onboarding
- [x] Onboard all new members
- [x] User Flow Overview
- [x] Github Overview 
- [x] Guest Intake Profile Overview
- [x] Assign Persona  Roles
  - [x] Assign Engineering PM (Ariel to start and maybe additional)
- [ ] Figma Overview for new designers 

## Process Improvements
- [x] MVP 1 and 2 rationalization flowchart: #749
- [x] Design Handoff Template #742 
- [x] Engineering Handoff Template #761 
- [x] Create new Goals Template to start in September (copy from "Future" section below)
- [x] Adjust Meeting breakouts to be persona focused
  - [x] PM Thursday meeting
  - [x] Breakout portion of Tuesday meeting
- [ ] #763
- [ ] #764
- [ ] #765
- [ ] Issue Naming Convention

## Project Planning
- [x] Update Milestones in Github #741
- [ ] Create Milestone Tracker (Project Plan)

## Project Board Clean Up and Alignment
- [x] Organize all issues into the appropriate milestones and statuses
   - [x] User Stories and Epics
   - [x] Engineering
   - [x] Design
   - [x] Research

Issues and Status as of Beginning of August
### Overall Team  - 126
 - Label Check Status
 - Issue Handover Status - Sanya 
    - #510 
    - #533 
    - #455 
    - #500 
 - Recurring Items **(12)**
 - Ice Box **(6)**
    - No Dependency label - 4 Issues
       - #380 
       - #432 
       - #433 
       - #755
   - Clarify dependency issue
   - Assigned to owner
      - #501 
      - #519 
      - #518 
      - #635 
 - New Issue Approval **(35)**
    - Owner assigned multiple issues
       - #604 
       - #618 
       - #617 
   - Missing "ready for" label
      - #745 
      - #196 
      - #572 
      - #456 
      - #611 
      - #315 
      - #338 
      - #604 
      - #607 
      - #608 
      - #651 
      - #305 
      - #618 
      - #357 
      - #3 
      - #764 
      - #765 
 - Prioritized Backlog **(8)**
 - For Review / Feedback Needed **(11)**
 - EPICS and Tracking **(1)**
 - In Progress **(20)**
 - UAT **(2)**
 - Legacy Tickets **(31)**
### Design - 18 (14%)
 - Recurring Items **(1)** 
 - Ice Box **(0)**
 - For Review / Feedback Needed **(0)**
 - New Issue Approval **(8)** 
 - Prioritized Backlog **(1)** 
 - EPICS and Tracking **(0)**
 - In Progress **(2)** 
 - UAT **(0)**
 - Legacy Tickets **(6)** 
### Research - 4 (3%)
 - Recurring Items **(1)** 
 - Ice Box **(0)**
 - For Review / Feedback Needed **(0)**
 - New Issue Approval **(1)** 
 - Prioritized Backlog **(0)** 
 - EPICS and Tracking **(0)**
 - In Progress **(1)** 
 - UAT **(0)**
 - Legacy Tickets **(1)** 
### Product   -  67 (54%)
 - Recurring Items **(7)**
 - Ice Box **(5)**
 - For Review / Feedback Needed **(10)**
 - New Issue Approval **(15)**
 - Prioritized Backlog **(2)**
 - EPICS and Tracking **(0)**
 - In Progress **(7)**
 - UAT **(1)**
 - Legacy Tickets **(20)**
### Engineering   -  37 (29%)
 - Recurring Items **(3)** 
 - Ice Box **(1)**
 - For Review / Feedback Needed **(1)**
 - New Issue Approval **(11)**
 - Prioritized Backlog **(5)**
 - EPICS and Tracking **(1)**
 - In Progress **(10)**
 - UAT **(1)**
 - Legacy Tickets **(4)**

# Future
### Recruiting
- [ ] Recruit Engineers
## Process Improvements and Documentation
- [ ] Determine how research integrates into the HUU development process
- [ ] Update our onboarding documentation (reference Sarah's onboarding [documentation](https://github.com/hackforla/peopledepot/issues/146))

## Project Planning
- [ ] Develop prioritization methodologies
- [ ] Pull existing documentation to determine need for Events Workshop
    - [ ] Re-oroganize requirements docs from google drive (maybe additional PM)
- [ ] Close out Milestone [6.1.1 - Functional MVP | Section 1 - Account Creation](https://github.com/hackforla/HomeUniteUs/milestone/18)

## Project Board Clean Up and Alignment

**Comment by lola3736** [comment]
Close August 2024 Goal, items not completed are transferred to September 2024 Goals if still applicable.

**Comment by lola3736** [comment]
Close August 2024 Goal, items not completed are transferred to September 2024 Goals if still applicable.
