### ISSUE TITLE
August Goals 2024

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#739]
By 8/31/2024

#### In progress:
- [ ] #440 
    - [ ] Guest/Host sign up: Add acknowledgement functionality
    - [ ] Move guest minimum expectations to sign up process
- [ ] Analysis and study anticipated to complete June 30th 

#### New Items:
- [ ] Coordinator notes: Save and cancel + editing screens for notes #519 
- [ ] Coordinator: Assign and reassign applications #518
- [ ] Host Dashboard #508 
- [ ] Host Application #509 
- [ ] Coordinator dashboard updates #501: Add status prior to submission. Add a column to have link to application

#### In progress:
- [ ] Account Creation
  - [ ] #703 
- [ ] Guest Intake Profile | #708
    - [ ]  #710
    - [ ] Guest form endpoints #636
- [ ] Incubator: deploy lower envs with end-to-end smoke test for SU/SI flows (i.e. existing functionality as of Mar 2024) #686
- [ ] Guest dashboard #572 #566
     - No one is currently working on #572
- [ ] Coordinator invite guest #520

#### New Items:
- [ ] Coordinator dashboard endpoint #651 
- [ ] Add acknowledgement during signup
- [ ] Guest intake profile mobile 

#### Final reviews:
- [ ] Host Matching Profile view 
- [ ] Guest/host sign up: add acknowledgement functionality #439

#### In Progress
- [ ] Host dashboard - bring to parity with guest + add steps for home inspection + to modify application after training
- [ ] Section 2 Coordinator User stories - need review, starting from Epic #454 

#### New:
- [ ] Host application -  bring to parity with guest + add a way to upload house or renters insurance
   - [ ] Update host dashboard to match guest (coordinator doesn't get assigned until after they submit their application)
- [ ] FAQ user story
- [ ] Coordinator update meeting & interview attendance/status for guest/host 
- [ ] Guest matching profile
- [ ] Create Guest, Host and Coordinator Sidebar stories
- [ ] Host experience for matching
- [ ] Downloadable intake profile instead of email
- [ ] Log of when guest and host worked on the app: V2
- [ ] Background Checks for Guest/Hosts
