### ISSUE TITLE
Breakdown HUU Project Milestones to be more granular

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#741]
### Overview
To enable clearer planning of issues, the PM team will work with the Engineering team to define sub-milestones for MVP.

### Action Items
- [x] PMs meet with Engineering Leads to discover their recommendations for milestones
- [x] Potentially include the high level figma flow sections as sub-milestones
- [x]  MVP phases
- [x] User Flow Sections
- [x] Engineering Milestones

**Comment by lasryariel** [comment]
@erikguntner @tylerthome would it be possible for one of you to provide your thoughts on what sub-milestones we should add to the project? 

It would be great if we can have your initial thoughts and then we could put it on the agenda for a team meeting.

CC: @lola3736

**Comment by erikguntner** [comment]
@lasryariel Definitely! We discussed two sub-milestones that we believe are attainable:

1. When a guest is invited by a coordinator the guest and all other users currently in the system can be viewed from the dashboard along with their current status.
2. A guest can fill out and submit their intake profile and have their status updated.

Ideally, these two milestones together will get us to a place where a coordinator can invite a guest -> that guest can accept the invite and fill out their intake profile -> A coordinator can view the guest's progress from the dashboard -> the status updates are reflected in the guest's dashboard.

How does that sound? Happy to answer any questions.

**Comment by lasryariel** [comment]
@erikguntner to be clear for number 1: you mean that all users can be seen from the Coordinator Dashboard right?

I like these milestones, but wonder if they are too granular. I'm inclined to go this granular but let's bring it up for tomorrow's meeting.

@lola3736 please would appreciate your thoughts on adding this level of detail to our milestones.

**Comment by erikguntner** [comment]
> @erikguntner to be clear for number 1: you mean that all users can be seen from the Coordinator Dashboard right?

Right. In this case all of the Hosts and Guests. 

> I like these milestones, but wonder if they are too granular.

We could broaden them to larger features like the Guest Dashboard, Guest Intake Profile, and Coordinator dashboard. These have the most work in progress. Maybe we identify the most crucial features for each in order to narrow things down a bit?

**Comment by lola3736** [comment]
@erikguntner @lasryariel Thanks for providing the initial milestone proposal. We are on the right track; we don't want it too granular nor to high level.  Each milestone should be considered a major deliverable to be viewed with our stakeholder (Boonie) and enable us to gauge where we are in the project.  The following proposal might work but we need to look at the whole flow to determine the right level of milestones. To ensure we continue to focus on work to be delivered, I will take this on as part of project management and provide a proposal for us to review:
- Six sections to create the end-to-end workflow:
  - Section 1: Account Creation
  - Section 2: Application and Onboarding Process
  - Section 3: Matching / Relationship Creation Process
  - Section 4: Relationship Management / Monitoring
  - Section 5: Relationship Termination Process
  - Section 6: Special Cases 
- For each of these sections, we need to determine the milestone delivery, might be easy to determine if we identify the tasks. 
Welcome your thoughts.
CC: @tylerthome
