### ISSUE TITLE
Project Board Hygiene - Clean Up and Alignment

### ISSUE THREAD

**Issue by lola3736** [hackforla/HomeUniteUs#769]
## Project Board Clean Up and Alignment
- [ ] Organize all issues into the appropriate milestones and statuses
   - [ ] User Stories and Epics
   - [ ] Engineering
   - [ ] Design
   - [ ] Research

Issues and Status as of Beginning of August
# Overall Team  - 109
- [Label Check](https://github.com/hackforla/HomeUniteUs/issues/354)
- Issue Handover Status - Sanya 
    - [ ] #510 
    - [ ] #533 
    - [ ] #455 
    - [ ] #500 
## Ice Box 
- No Dependency label - 4 Issues
   - [ ] #380 
    - [ ] #432 
    - [ ] #433 
    - [ ] #755
- Clarify dependency issue
    - [ ] #362 
    - [ ] #623 Okay to close? @tylerthome 
    - [ ] #501 
    - [ ] #519 
    - [ ] #380 
    - [ ] #432 
    - [ ] # 433
    - [ ] #518 
- Assigned to more than 1 owner
    - [ ] #501   
- Assigned to an owner
    - [ ] #501 
    - [ ] #519 
    - [ ] #518 
    - [ ] #635 
## New Issue Approval 
- Owner assigned multiple issues
    - [ ] #604 
    - [ ] #618 
    - [ ] #617 
- Missing Labels 
  - Ready for
    - [ ] #745 
    - [x] #196 
    - [ ] #572 
    - [ ] #456 Also, doesnt include all the user stories
    - [ ] #611 Also, this issue is for both Guest and Host, should we create one for each.
    - [ ] #315 
    - [ ] #338 
    - [ ] #604 
    - [ ] #607 
    - [ ] #608 718
    - [ ] #651 
    - [ ] #305 
    - [ ] #618 
    - [ ] #357 
    - [ ] #3 
    - [ ] #764 
    - [ ] #765 
 - Complexity 
   - [ ] #375
- Clarify Issue Status
  - [ ] #745 
- Confirm Complexity - Engineering
  - [x] #196 
  - [ ] #607 
  - [ ] #608 
  - [ ] #651 
  - [ ] #572 
  - [ ] #757       
  - [ ] #778 
## Prioritized Backlog 
- Confirm issue is ready for prioritization
    - [ ] #719 
    - [ ] #718 
    - [ ] #716 
    - [ ] #720 
    - [x] #711 
    - [ ] #652 
    - [ ] #528 
    - [ ] #475 
    - [ ] #650 
    - [ ] #709      
- Need to add Design Handoff
- Need to add Dev Handoff 
### Issues Tracking 
- Coordinator
- Guest
- Host

**Comment by lola3736** [comment]
Close issue, no longer applicable.
