### ISSUE TITLE
Reorganize Figma Designs related to #454 Section 2 | Coordinator Epic

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#772]
### Overview
- We need to organize the Figma file to make it easy to find the latest designs related to #454 so that we can clearly identify what still needs to be worked on.

### Action Items
- [x] Design Lead: Review and assign Designer - Priyanka Assigned, Nihan will shadow.
- [x] Organize designs
- [x] Review with Design Lead
- [x] Review with PM team

Once the organizing is complete, the Coordinator pod will be equipped to work together to create and prioritize design issues.
 
- Figma has been reorganized. Coordinator related designs are in their own section:
![image](https://github.com/user-attachments/assets/0ff68664-d53c-4c7c-8f74-340fb1b5fb78)

### Resources/Instructions
- [Master Figma File](https://www.figma.com/design/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?t=d0gQO6HBEc1k62Ji-0)

**Comment by lasryariel** [comment]
Figma has been reorganized. Coordinator related designs are in their own section:
![image](https://github.com/user-attachments/assets/0ff68664-d53c-4c7c-8f74-340fb1b5fb78)

@prigupta18 I am closing this issue for you and moving it to Done status.
