### ISSUE TITLE
Design for #454 Section 2 | Coordinator Epic

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#784]
### Overview
- This issue is for tracking design work related to #454, we need to design a Dashboard page where a Coordinator can see all Guests/Hosts, so the Coordinator can manage guest/hosts through the application and onboarding process.

### Action Items
- Assign and Prep
  - [ ] Design Lead: Review User Story and assign Designer
  - [ ] Designer: Review User Story
  - [ ] Designer: Work with PM and Design Lead to clarify any questions about the User Story
  - [ ] Designer: Work with Design Lead to determine appropriate place/page to Draft Design in Figma
- Draft and Review:
   - [ ] Designer: Draft Design
   - [ ] Designer: Add Screenshots of design and link to Figma page in a comment
   - Let Product know that the design is ready for review
      - [ ] Designer: Change Issue Status to "For Review/Feedback Needed"
      - [ ] Designer: Add Label "Ready for: Product"
      - [ ] Designer: Tag the PM of the related User Story in a comment below and let them know that a draft is ready for review
   - [ ] Product: Review Design Screenshots and provide feedback
   - [ ] Repeat above steps until design is approved
- Engineering Handoff
   - [ ] Designer and Product: Review with Engineering for questions
   - [ ] Designer: Add link to Figma and Screenshots to a comment in the linked User Story

**Comment by lasryariel** [comment]
- add profile pic icon to sticky section
- what does expand look like while still in side view
- separate intake profile approval from overall approval
