### ISSUE TITLE
October 2024 Goals

### ISSUE THREAD

**Issue by lola3736** [hackforla/HomeUniteUs#806]
# October Goals
## Recruiting 
- [x] Recruit 2 designer for Guest Persona
- [ ] Recruit 1 Researchers - No longer required
- [ ] Determine Engineering Team structure (possibly per persona)
  - [ ] Recruit Engineers
- [x] Onboard all new members
   - [x] Figma Overview for new designers 
   - [x] Design User Flow Overview

## Process Improvements and Documentation
- [ ] Design Best Practice - Finalize in November 2024
- [ ] Update our onboarding documentation (reference Sarah's onboarding [documentation](https://github.com/hackforla/peopledepot/issues/146)) - 
- [ ] Create new Goals Template to start in September (copy from "Future" section below) 
- [ ] #763 - Team workflow
- [ ] #764
- [ ] #765
- [ ] Issue Naming Convention

## Project Plan
- [ ] Draft Project Plan - November 2024
- [ ] Draft Product Requirement Document (PRD)
- [ ] Develop MVP Roadmap - November 2024
- [x] Update Milestone using 311 as a guide
   - [ ] Develop prioritization methodologies - Proposed methodology (MoSCow)
     - [ ] Must-Have: Essential features for the MVP
     - [ ] Should-Have: Important but not critical for the MVP. These can be delivered after the MVP launch.
     - [ ] Could-Have: Nice-to-have features that can be added later without affecting the core functionality
     - [ ] Won’t-Have: Features that are not relevant at this stage but could be revisited later.
- [ ] Pull existing documentation to determine need for Events Workshop
    - [ ] Re-oroganize requirements docs from google drive (maybe additional PM)
- [ ] Close out Milestone [6.1.1 - Functional MVP | Section 1 - Account Creation](https://github.com/hackforla/HomeUniteUs/milestone/18)

## Product
- [x] Complete Draft List of Features and share with team ([HUU Roadmap & Prioritization](https://docs.google.com/spreadsheets/d/1uM287TOz20jnXPS4kRe0Dt5GlhnPbNRYBHHOxcamCJ0/edit?gid=343529642#gid=343529642))

## Dev 
- #790
- #771

## Design
- [x] Design System - finalize styling and craft at least 5-8 UI components, not including documentation.
- [ ] User Flow
    - [ ] For Guest+Host personas, goal is to finalize userflow + responsive web wireframe for issue #533 and #456. **_Note: mobile app is out of scope._**
    - [x] For Coordinator, goal is to finalize user flow + desktop wireframe for issue #736
- [ ] Determine how research integrates into the HUU development process

## Research
- [ ] Start a gameplan on establishing a research function and how it can integrate into the HUU development process. Work with @lasryariel and add the process matrix.
- [x] Start on Research best practice slide deck/presentation
- [ ] Drafts of detailed documentation from desk research on the 3 persona profiles
 
## Project Board Clean Up and Alignment
[Weekly label and board check](https://github.com/hackforla/HomeUniteUs/issues/354)

**Comment by lola3736** [comment]
@lasryariel @nlvan please review the draft October 2024 and provide feedback, thanks much.

**Comment by nlvan** [comment]
@lola3736 
Looks great to me. I'd like to add in a few things:

- We'll only need to recruit 1 more UX researcher

Design
- I'm working with Priyanka to finalize design best pracice, specifically adding guidance on how to work with and user Design System. However, I'm not confident on completing this in October because she has a lot on her plate for the Coordinator design work.
- For Guest+Host personas, goal is to finalize userflow + desktop (hopefully mobile as well) wireframe for issue #533 and #456
- For Coordinator,  goal is to finalize userflow + desktop wireframe for issue  #519, #635, #731. For mobile, I haven't seen it has been touched on yet, maybe @lasryariel can verify
- For Design System, goal is finalize styling and craft at least 5-8 UI components, not including documatation.

Research
- Start a gameplan on establishing a research function and how it can integrate into the HUU development process. @lasryariel I'd love to harsh it out with you and add this to the process matrix that you make.
- Start on Research best practice slidedeck/presentation
- Drafts of detailed documentation from desk resarch on the 3 persona profiles
