### ISSUE TITLE
HUU: PM/ORG Agenda and Meeting Minutes

### ISSUE THREAD

**Issue by lola3736** [hackforla/HomeUniteUs#816]
### Overview
This issue tracks the agenda for the PM/Org meetings for the HomeUniteUS project

### Resources
Add a link to each comment below (each one being an agenda and meeting minutes

### Minutes Template
```
## Agenda and Minutes 2022-02-1

### Prework
- [ ] label audit #354

### Roll Call

- [ ] Kristy
- [ ] Regan
- [ ] Sanya
- [ ] Kristelle
- [ ] Denisse
- [ ] Ben
- [ ] Raji
- [ ] Bonnie


#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/HomeUniteUs/projects/3#column-15433668)
 - [ ] Accountability and Support Check
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/HomeUniteUs/issues/assigned/ExperimentsInHonesty)
       - [ ] [Regan](https://github.com/hackforla/HomeUniteUs/issues/assigned/JRHutson)
       - [ ] [Kristy](https://github.com/hackforla/HomeUniteUs/issues/assigned/kpoints)
       - [ ] [Denisse](https://github.com/hackforla/HomeUniteUs/issues/assigned/Dsequ)
       - [ ] [Ben](https://github.com/hackforla/HomeUniteUs/issues/assigned/rossbb)
       - [ ] [Kristelle](https://github.com/hackforla/HomeUniteUs/issues/assigned/k-gumarama)
       - [ ] [Sanya](https://github.com/hackforla/HomeUniteUs/issues/assigned/sanya301)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)

#### New Items and Items from Previous Meeting

#### Actions taken or notes about stuff from the meeting:

#### New Task Items

**Comment by lola3736** [comment]
## 2024-10-03 Meeting Agenda
### All Team Meeting Action Items
- Jon to provide mock-up of profile to show scalability
- Team to incorporate Bonnie's feedback
- Anything else
### Onboarding/Offboarding Clarification
- [Roster - whats "Public & Note" on checklist](https://github.com/hackforla/HomeUniteUs/issues/396)
- Do design /dev lead need 1Password
- Design and Dev team members are that are no longer with us have access to the following, who to contact to remove:
   - [UI UX write](https://github.com/orgs/hackforla/teams/home-unite-us?query=eduardo)
   - [Hack for LA Engineering Write](https://github.com/orgs/hackforla/teams/home-unite-us?query=joshua)
### Project Plan
- [Milestones: which items are mandatory for all Projects](https://github.com/hackforla/product-management/wiki/Milestones)
- Research: Does HFLA use transcription services for research and interviewing
- Clarification on SPY Handbook 
    - There are 3 versions: version 1, version 2 and 2024
       - Consistent across versions
          - 4 Personas; 
             - 1 Host Home Coordinator: maintains / manages the program, main contact for the hosts
             - Case Manager: supports the Guests, provides referral to the program
             - Host
             - Guest 
         - Some minor differences in the handbook recommended design of the program and SPY's implementation/process based on the documents provided. 
            - Persona's
            - HHC interaction with Guest
- There is a competitive / Comparative Analysis - need clarification
- [The previous Project Board appeard to have 4 personnas](https://drive.google.com/drive/u/1/folders/1Dj8qQfsHY4Meu6BTNYsGeUNWd_x1iaW0)
- [In progress and draft of Oct Goals](https://github.com/hackforla/HomeUniteUs/issues/806)
  - PRD documentation
  - List of features
  - Design system
  - User Flow 
  - Migration to AWS Incubator
  - [Weekly Label Check](https://github.com/hackforla/HomeUniteUs/issues/354)

**Comment by lola3736** [comment]
## 2024-10-10 Meeting Agenda
### All Team Meeting Action Items
- Jon to provide mock-up of profile to show scalability
- [Team to incorporate Bonnie's feedback](https://github.com/hackforla/HomeUniteUs/issues/533)
- Anything else
### Onboarding/Offboarding Clarification
- [Roster - whats "Public & Note" on checklist](https://github.com/hackforla/HomeUniteUs/issues/396)
- Do design /dev lead need 1Password
- Design and Dev team members are that are no longer with us have access to the following, who to contact to remove:
   - [UI UX write](https://github.com/orgs/hackforla/teams/home-unite-us?query=eduardo)
   - [Hack for LA Engineering Write](https://github.com/orgs/hackforla/teams/home-unite-us?query=joshua)
### Project Plan
- [Milestones: which items are mandatory for all Projects](https://github.com/hackforla/product-management/wiki/Milestones)
- Research: Does HFLA use transcription services for research and interviewing
- There is a competitive / Comparative Analysis - need clarification
- [The previous Project Board appeared to have 4 personnas](https://drive.google.com/drive/u/1/folders/1Dj8qQfsHY4Meu6BTNYsGeUNWd_x1iaW0)
- [In progress and draft of Oct Goals](https://github.com/hackforla/HomeUniteUs/issues/806)
  - PRD documentation
  - List of features
  - Design system
  - User Flow 
  - Migration to AWS Incubator
  - [Weekly Label Check](https://github.com/hackforla/HomeUniteUs/issues/354)
## Summary Meeting Notes

 - Action items from 10-03-2024 Meeting
  - [ ] Draft milestones for review
  - [ ] Document test transcription 
  - [ ] Include Admin Coordinator features to Coordinator Persona
  - [ ] Check team roster to ensure all team members have their GitHub profile as "Public"

**Comment by lola3736** [comment]
## 2024-10-24 Meeting Agenda
### Recurring  
- [Weekly Label Audit](https://github.com/hackforla/HomeUniteUs/issues/354)
- [Oct Goals](https://github.com/hackforla/HomeUniteUs/issues/806)
### Project Plan
- Draft PRD - in progress
- List of features
- Design system
- User Flow 
- Migration to AWS Incubator
## Summary Meeting Notes
### Action Items
- Action items from 10-17-2024
  - [ ] Add "dummy data" feature label
  - [ ] Change "points" label to follow HFLA standard verbiage 
  - [ ] For issues with draft label:
    - [ ] Issue owner to:
       - [ ] Assign to themselves
       - [ ] Review to determine the status and additional action needed
       - [ ] Assigned "Ready for label" as appropriate 
- Action items from 10-10-2024
  - [ ] Update Wiki page 
  - [ ] Update competitive / Comparative Analysis 
 - Action items from 10-03-2024 Meeting
   - [ ] Draft milestones for review
   - [ ] Document test transcription 
   - [ ] Include Admin Coordinator features to Coordinator Persona
   - [ ] Check team roster to ensure all team members have their GitHub profile as "Public"

**Comment by lola3736** [comment]
## 2024-11-07 Meeting Agenda
### Recurring  
- [Weekly Label Audit](https://github.com/hackforla/HomeUniteUs/issues/354)
### Project Update
- [Wiki - progress to date](https://github.com/hackforla/HomeUniteUs/wiki) 
- Design system - in progress
- User Flow - in progress
- Migration to AWS Incubator - completed
### New Items
- CoP meeting, unable to initiate Note taker, is there a blocker to AI
- Design team
   - Which HiFi for Guest/Hostn to use
   - What's is "Brand Guide Line"?
   - Team work that you didnt see
     - [Jiehong](https://www.figma.com/design/BNWqZk8SHKbtN1nw8BB7VM/HUU-Main-File---10%2F2024?node-id=2353-17357)
     - [Julia](https://www.figma.com/design/BNWqZk8SHKbtN1nw8BB7VM/HUU-Main-File---10%2F2024?node-id=1373-8185&node-type=canvas&t=u6k7ht6b5M1e0Czp-0)
- Team workflow for review and approval of product design and development
- Received email on Amazon AWS account closure
- [Team Roster Cleanup](https://docs.google.com/spreadsheets/d/1Qp0iLv5Bvafip9y8gu9AUy2d5800916ybJ4_YElmyYM/edit?gid=1806338047#gid=1806338047)

**Comment by lola3736** [comment]
## 2024-11-14 Meeting Agenda
### Recurring  
- [Weekly Label Audit](https://github.com/hackforla/HomeUniteUs/issues/354)
### New Items
- Team workflow for review and approval of product design and development (in progress)
  - High Level
    - Directional perspective - to be discussed with PM and Design Lead and maybe Dev Lead - small audience
    - Design, PM and Deve Lead approval of wireframes and hifi design prior to Bonnie's review 
      - Include Dev team member during Product and Design collaboration 
- Received email on Amazon AWS account closure

---
Roll call
- [x] Bonnie Wolf
- [x] Lola Sarumi

**Comment by lola3736** [comment]
[Website still not correctly updated](https://www.hackforla.org/projects/home-unite-us)

**Comment by lola3736** [comment]
## 2025-01-11 Meeting Agenda
### Recurring  
- [Weekly Label Audit](https://github.com/hackforla/HomeUniteUs/issues/354)
- Past items
### New Items
https://github.com/hackforla/product-management/wiki/Preparing-for-team-meetings:-tasks-for-PMs
