### ISSUE TITLE
[DUPLICATE] Epic: Marketing: Home Unite Us

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#821]
THIS IS A DUPLICATE AND SHOULD BE DELETED

accidentally created this issue in our repo when it should have been created in the marketing repo. corrected issue is here: https://github.com/hackforla/marketing/issues/62

### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [x] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [x] Copy the URL and add it to resource 2.01
   - [x] add all issue links to a comment on this issue under this heading
   ```
   ### Home Unite Us Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [x] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [x] Go to the project repo issue tab (resource 2.02)
  - [x] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project or CoP's repo issue searches
   ```
     - [x] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g., [is:issue marketing ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+marketing))
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [x] add a label `ready for marketing lead`
- [x] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [label: P: Home Unite Us](https://github.com/hackforla/marketing/labels/P%3A%20Home%20Unite%20Us)
- 2.02 [Home Unite Us Issues](https://github.com/hackforla/HomeUniteUs/issues)

**Comment by lasryariel** [comment]
### Home Unite Us Team Task issues
- [Define Marketing Objectives for Home Unite Us project](https://github.com/hackforla/marketing/issues/22)

**Comment by lasryariel** [comment]
### Project's repo issue searches

**Comment by lasryariel** [comment]
accidentally created this issue in our repo when it should have been created in the marketing repo. corrected issue is here: https://github.com/hackforla/marketing/issues/62
